name: Node Continuous Integration

on:
  pull_request:
    branches: [ main ]


jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test
      - run: npm run build
      
- name: Microsoft Teams (Generic)
  # You may pin to the exact commit or the version.
  # uses: aliencube/microsoft-teams-actions@dd5e839bd9f0a79a162d8b6a79065ff525be44b9
  uses: aliencube/microsoft-teams-actions@v0.8.0
  with:
    # Incoming webhook URI to Microsoft Teams
    webhook_uri: 
    # Message title
    title: # optional, default is 
    # Message summary
    summary: # optional, default is 
    # Message text
    text: # optional, default is 
    # Message theme color
    theme_color: # optional, default is 
    # JSON array for message sections
    sections: # optional, default is 
    # JSON array for message actions
    actions: # optional, default is 